file doesn't exist:
  $ owi wasm script concrete not_exists.wat
  Usage: owi wasm script concrete [--help] [--no-exhaustion] [OPTION]…
         FILE…
  owi: FILE… arguments: no file 'not_exists.wat'
  [124]
