name: build-debian-ocaml-latest
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zapashcanon/gitea-ocaml-ci:latest
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: test
        run: |
          eval "$(opam env)"
          opam install . --depext-only --with-test --with-doc --with-dev-setup -y
          opam install . --deps-only --with-test --with-doc --with-dev-setup -y
          opam exec -- dune build @install
          opam exec -- dune runtest
