name: build-macos-ocaml-latest
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler:
          - "5.3"
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: checkout-submodules
        run: |
          git submodule update --init test/script/reference
          git submodule update --init test/c/collections-c/files
          mv .git .git.tmp # prevents opam from checking-out submodules
      - name: cache
        id: cache-opam
        uses: actions/cache@v4
        env:
          cache-name: cache-opam-build
        with:
          path: |
            ~/work/owi/owi/_opam/
          key: ${{ runner.os }}-build-${{ matrix.ocaml-compiler }}-${{ env.cache-name }}-${{ hashFiles('**/*.opam') }}
      - name: setup-ocaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
          opam-pin: true
          allow-prerelease-opam: false
      - name: depext
        run: |
          rustup update
          rustup target add wasm32-unknown-unknown
          brew update
          brew upgrade
          brew install pkgconf zig # TODO: remove zig once the conf-zig package works
          opam install . --depext-only --with-test --with-doc
      - name: setup
        if: steps.cache-opam.outputs.cache-hit != 'true'
        run: |
          opam install . --deps-only --with-test --with-doc --with-dev-setup
          opam clean --switch-cleanup
      - name: build
        run: |
          export PATH="$(brew --prefix llvm@15)/bin/:$PATH" # macossucks
          opam exec -- dune build @install
          mv .git.tmp .git # bring it back, we won't call opam anymore from now on
          opam exec -- dune runtest
          ODOC_WARN_ERROR=true opam exec -- dune build @doc 2> output.txt || true
          $(exit $(wc -l output.txt | cut -d " " -f1))
          opam exec -- dune build @fmt || (echo "\n⚠️ please run \`dune fmt\` and try again" && exit 1)
          git diff --exit-code owi.opam || (echo "⚠️ please run \`dune build\`, commit the changes to owi.opam, and then try again" && exit 1)
