name: build-ubuntu
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kumikode/owi-ci:ubuntu-latest
      options: --user root
    steps:
      - name: Check Rust
        run: |
          set -x
          whoami
          echo "HOME=$HOME"
          echo "RUSTUP_HOME=$RUSTUP_HOME"
          echo "CARGO_HOME=$CARGO_HOME"
          rustup show
          rustup toolchain list
          rustc --version
          rustup target list --installed
      - name: test
        run: |
          set -x

          git clone https://github.com/${{ github.repository }}.git
          cd $(basename ${{ github.repository }})

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-${{ github.event.pull_request.number }}
            git checkout pr-${{ github.event.pull_request.number }}
          else
            git checkout ${{ github.ref_name }}
          fi

          # Build and test
          dune build @install
          dune build @quicktest
