name: check-copyright-headers
on:
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  license-check:
    name: Check license headers on new files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Check License Header
        run: |
          files=$(git ls-files '*.ml' '*.mli' | grep -v "^doc/")
          missing_copyright=false

          for f in $files; do
            if ! grep -q "Copyright © 2021-2026 OCamlPro" "$f"; then
              echo "missing copyright header in: $f"
              missing_copyright=true
            fi
          done

          if [ "$missing_copyright" = true ]; then
            exit 1
          fi
