name: deploy-static-executable
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kumikode/owi-ci:alpine-static-latest
      options: --user root
    steps:
      - name: build
        run: |
          set -x

          git clone https://github.com/${{ github.repository }}.git
          cd $(basename ${{ github.repository }})

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-${{ github.event.pull_request.number }}
            git checkout pr-${{ github.event.pull_request.number }}
          else
            git checkout ${{ github.ref_name }}
          fi

          dune build @install --profile staticlink
          dune install --prefix /tmp/owi-install --profile staticlink

          mkdir -p "$GITHUB_WORKSPACE/dist"
          tar -C /tmp/owi-install -czf "$GITHUB_WORKSPACE/dist/owi-linux-x86_64-musl.tar.gz" .
      - name: upload artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: owi-linux-x86_64-musl
          path: dist/owi-linux-x86_64-musl.tar.gz
